name: Security Scan for Vue.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run vue Cli Service
        run: npm i @vue/cli-service

      - name: Run ESLint
        run: npm run lint

  audit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run npm audit
        run: npm audit fix --force
#        run: npm audit --audit-level=high

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo chuthanhlam | docker login -u thanhlam0822 --password-stdin

      - name: Build Docker image
        run: |
          docker build -t my-vue-app:latest .

      - name: Push Docker image
        run: docker tag my-vue-app:latest thanhlam0822/my-vue-app:latest && docker push thanhlam0822/my-vue-app:latest

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.38.2/trivy_0.38.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.38.2_Linux-64bit.deb

      - name: Scan Docker image for vulnerabilities
        run: trivy image my-vue-app:latest --exit-code 1 --severity HIGH,CRITICAL
